- name: setup nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: mvaen-setup.yaml
- name: setup nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: setup-app.yaml   
- name: download package
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app  
- name: moving "{{ component }}".jar
  ansible.builtin.command: mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: /app     
