- name: setting up nodejs repos.
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
- name: installing node js
  ansible.builtin.yum:
    name: nodejs
    state: installed  